version: '3'

services:
  fastapi:
    image: subhashchandran/assignment-03-fastapi:v2
    ports:
      - "8000:8000"
  streamlit:
    image: subhashchandran/assignment-03-streamlit:v2
    ports:
      - "8501:8501"