name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FINAL_PROJ_ENV: ${{ secrets.FINAL_PROJ_ENV }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Requirements.txt

    - name: Set environment variables
      run: echo "$FINAL_PROJ_ENV" >> .env

    - name: Run pytest
      run: pytest test.py
